document.addEventListener("DOMContentLoaded", () => {
      const startButton = document.getElementById("start-game");
        const toggleMusicButton = document.getElementById("toggle-music");
          const playerHand = document.getElementById("player-hand");
            const computerHand = document.getElementById("computer-hand");
              const playedCards = document.getElementById("played-cards");
                const levelDisplay = document.getElementById("level-display");
                  const backgroundMusic = document.getElementById("background-music");

                    const suits = ["♠", "♥", "♣", "♦"];
                      const values = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];

                        let deck = [];
                          let playerScore = 0;
                            let computerScore = 0;
                              let level = 1;
                                let isMusicPlaying = false;

                                  // Initialize deck
                                    const initializeDeck = () => {
                                        deck = [];
                                            suits.forEach(suit => {
                                                  values.forEach(value => {
                                                          deck.push({ suit, value, score: values.indexOf(value) + 1 });
                                                                });
                                                                    });
                                                                        shuffleDeck();
                                                                          };

                                                                            // Shuffle deck
                                                                              const shuffleDeck = () => {
                                                                                  deck.sort(() => Math.random() - 0.5);
                                                                                    };

                                                                                      // Deal cards
                                                                                        const dealCards = () => {
                                                                                            playerHand.innerHTML = "";
                                                                                                computerHand.innerHTML = "";

                                                                                                    const playerCards = deck.splice(0, 5);
                                                                                                        const computerCards = deck.splice(0, 5);

                                                                                                            playerCards.forEach(card => {
                                                                                                                  const cardElement = document.createElement("div");
                                                                                                                        cardElement.classList.add("card");
                                                                                                                              cardElement.textContent = `${card.value} ${card.suit}`;
                                                                                                                                    cardElement.addEventListener("click", () => playCard(card, cardElement, computerCards));
                                                                                                                                          playerHand.appendChild(cardElement);
                                                                                                                                              });

                                                                                                                                                  computerCards.forEach(card => {
                                                                                                                                                        const cardElement = document.createElement("div");
                                                                                                                                                              cardElement.classList.add("card");
                                                                                                                                                                    cardElement.textContent = "?";
                                                                                                                                                                          computerHand.appendChild(cardElement);
                                                                                                                                                                              });
                                                                                                                                                                                };

                                                                                                                                                                                  // AI Logic based on Level
                                                                                                                                                                                    const chooseComputerCard = (computerCards, playerCard) => {
                                                                                                                                                                                        if (level <= 100) {
                                                                                                                                                                                              return computerCards[Math.floor(Math.random() * computerCards.length)];
                                                                                                                                                                                                  } else if (level <= 300) {
                                                                                                                                                                                                        const higherCards = computerCards.filter(c => c.score > playerCard.score);
                                                                                                                                                                                                              return higherCards.length > 0
                                                                                                                                                                                                                      ? higherCards[Math.floor(Math.random() * higherCards.length)]
                                                                                                                                                                                                                              : computerCards[Math.floor(Math.random() * computerCards.length)];
                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                        const higherCards = computerCards.filter(c => c.score > playerCard.score);
                                                                                                                                                                                                                                              if (higherCards.length > 0) {
                                                                                                                                                                                                                                                      return higherCards.reduce((lowest, card) => (card.score < lowest.score ? card : lowest));
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                  return computerCards.reduce((lowest, card) => (card.score < lowest.score ? card : lowest));
                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                          // Play a card
                                                                                                                                                                                                                                                                            const playCard = (playerCard, cardElement, computerCards) => {
                                                                                                                                                                                                                                                                                playedCards.innerHTML = "";
                                                                                                                                                                                                                                                                                    cardElement.classList.add("played");
                                                                                                                                                                                                                                                                                        playedCards.appendChild(cardElement);

                                                                                                                                                                                                                                                                                            playerHand.removeChild(cardElement);

                                                                                                                                                                                                                                                                                                const computerCard = chooseComputerCard(computerCards, playerCard);
                                                                                                                                                                                                                                                                                                    const computerCardElement = document.createElement("div");
                                                                                                                                                                                                                                                                                                        computerCardElement.classList.add("card", "played");
                                                                                                                                                                                                                                                                                                            computerCardElement.textContent = `${computerCard.value} ${computerCard.suit}`;
                                                                                                                                                                                                                                                                                                                playedCards.appendChild(computerCardElement);

                                                                                                                                                                                                                                                                                                                    const cardIndex = computerCards.indexOf(computerCard);
                                                                                                                                                                                                                                                                                                                        if (cardIndex > -1) computerCards.splice(cardIndex, 1);

                                                                                                                                                                                                                                                                                                                            if (playerCard.score > computerCard.score) {
                                                                                                                                                                                                                                                                                                                                  playerScore++;
                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                            computerScore++;
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                    updateScores();

                                                                                                                                                                                                                                                                                                                                                        if (playerHand.children.length === 0) {
                                                                                                                                                                                                                                                                                                                                                              nextLevel();
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                      const updateScores = () => {
                                                                                                                                                                                                                                                                                                                                                                          document.getElementById("player-score").textContent = playerScore;
                                                                                                                                                                                                                                                                                                                                                                              document.getElementById("computer-score").textContent = computerScore;
                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                  const nextLevel = () => {
                                                                                                                                                                                                                                                                                                                                                                                      level++;
                                                                                                                                                                                                                                                                                                                                                                                          if (level > 600) {
                                                                                                                                                                                                                                                                                                                                                                                                alert("Congratulations! You've completed all levels!");
                                                                                                                                                                                                                                                                                                                                                                                                      localStorage.removeItem("cardGameProgress");
                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                    saveProgress();
                                                                                                                                                                                                                                                                                                                                                                                                                        showLevelTransition();
                                                                                                                                                                                                                                                                                                                                                                                                                            updateDifficultyIndicator();
                                                                                                                                                                                                                                                                                                                                                                                                                                levelDisplay.textContent = `Level: ${level}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                    initializeDeck();
                                                                                                                                                                                                                                                                                                                                                                                                                                        dealCards();
                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                            const showLevelTransition = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                const levelTransition = document.getElementById("level-transition");
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const transitionText = document.getElementById("transition-text");

                                                                                                                                                                                                                                                                                                                                                                                                                                                        transitionText.textContent = `Level ${level}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            levelTransition.classList.add("visible");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      levelTransition.classList.remove("visible");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }, 2000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const updateDifficultyIndicator = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const difficultyIndicator = document.getElementById("difficulty-indicator");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (level <= 100) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            difficultyIndicator.textContent = "Difficulty: Easy";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else if (level <= 300) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      difficultyIndicator.textContent = "Difficulty: Medium";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                difficultyIndicator.textContent = "Difficulty: Hard";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const saveProgress = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const gameState = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  level,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        playerScore,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              computerScore,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      localStorage.setItem("cardGameProgress", JSON.stringify(gameState));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const loadProgress = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const savedState = localStorage.getItem("cardGameProgress");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (savedState) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { level: savedLevel, playerScore: savedPlayerScore, computerScore: savedComputerScore } = JSON.parse(savedState);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              level = savedLevel || 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    playerScore = savedPlayerScore || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          computerScore = savedComputerScore || 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                levelDisplay.textContent = `Level: ${level}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updateDifficultyIndicator();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updateScores();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const toggleMusic = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isMusicPlaying) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             backgroundMusic.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    isMusicPlaying = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundMusic.play();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    isMusicPlaying = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            toggleMusicButton.addEventListener("click", toggleMusic);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              startButton.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  loadProgress();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      initializeDeck();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          dealCards();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
